export const SIGN_IN_BEGIN = 'SIGN_IN_BEGIN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_OUT_BEGIN = 'SIGN_OUT_BEGIN';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';
export const AUTHENTICATION_CHECK_BEGIN = 'AUTHENTICATION_CHECK_BEGIN';
export const AUTHENTICATION_CHECK_END = 'AUTHENTICATION_CHECK_END';
